import json
import logging

import viktor as vkt

from agent import agent_sync_stream
from table_tool import TableTool

logger = logging.getLogger(__name__)


def get_table_visibility(params, **kwargs):
    """Check if table view should be visible"""
    if not params.chat:
        # Clear storage when chat is reset
        entities = vkt.Storage().list(scope="entity")
        for entity in entities:
            if entity == "show_table":
                vkt.Storage().delete("show_table", scope="entity")
            if entity == "TableTool":
                vkt.Storage().delete("TableTool", scope="entity")

    try:
        out_bool = vkt.Storage().get("show_table", scope="entity").getvalue()
        print(f"{out_bool=}")
        if out_bool == "show":
            return True
        return False
    except Exception:
        # If there is no data, then view is hidden.
        return False


class Parametrization(vkt.Parametrization):
    intro = vkt.Text(
        """
        ## Revit MCP Agent

        This Viktor app talks to the local C# Revit MCP endpoint at `CSHARP_MCP_SERVER_URL`
        and discovers tools through the MCP protocol using OpenAI Agents Python.

        The agent can also display data in table format using the `generate_table` tool.
        """
    )
    chat = vkt.Chat(
        "Ask the Revit bridge",
        method="call_llm",
        visible=True,
        flex=100,
    )


class Controller(vkt.Controller):
    label = "Revit MCP Agent"
    parametrization = Parametrization

    def call_llm(self, params, **kwargs) -> vkt.ChatResult | None:
        """Multi-turn conversation between the user and the agent."""

        if not params.chat:
            return None

        conversation_history = params.chat.get_messages()
        if not conversation_history:
            return None

        chat_history = [
            {"role": str(message["role"]), "content": str(message["content"])}
            for message in conversation_history
        ]

        text_stream = agent_sync_stream(
            chat_history=chat_history,
            show_tool_progress=True,
        )
        return vkt.ChatResult(params.chat, text_stream)

    @vkt.TableView("Table Tool", width=100, visible=get_table_visibility)
    def table_view(self, params, **kwargs) -> vkt.TableResult:
        """Display table data generated by the agent"""
        if not params.chat:
            try:
                vkt.Storage().delete("TableTool", scope="entity")
            except Exception:
                pass
        try:
            raw = (
                vkt.Storage()
                .get("TableTool", scope="entity")
                .getvalue_binary()
                .decode("utf-8")
            )
            logger.info(f"Table raw data: {raw}")
            tool_input = TableTool.model_validate_json(raw)
            logger.info(f"Table tool_input: {tool_input}")
            return vkt.TableResult(
                data=tool_input.data, column_headers=tool_input.column_headers
            )
        except Exception as e:
            logger.exception(f"Error in table_view: {e}")
            return vkt.TableResult([["Error", "using Tool"]])
